### ISSUE TITLE
Action Mailer endpoint

### ISSUE THREAD

**Issue by josephhilby** [Consultancy-2208/west_fl_wx_be#4]
Create a email endpoint that, when called by the FE app (Post ‘/api/v1/email?address=mstang@turing.edu’), will query the Twitter api, the NWS API, and  and generate an email, to be sent to the user, that includes:

A list of all current weather alerts in FLZ202, that are "Actual", and "Severe" or "Extreme":
- Each Alert should include:
  - :effective
  - :expires
  - :description
  - :instruction

The last three tweets from both @fl511_panhandl & @bereadyescambia (as filtered by twitter api service).

**Comment by josephhilby** [comment]
Docs: https://guides.rubyonrails.org/action_mailer_basics.html

**Comment by efuchsman** [comment]
Will rolled into a new updated issue
